name: t_store
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.20.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE
  image_picker: ^1.1.2
  permission_handler: ^10.4.3
  auto_size_text: ^3.0.0
  awesome_snackbar_content: ^0.1.4
  flutter_icon_snackbar: ^1.2.1
  chatview: ^2.4.0
  emoji_picker_flutter: ^3.0.0
  path_provider: ^2.0.11
  file_picker: ^5.3.0    # For Google Drive or file picker
  cached_network_image: ^3.2.3
  # shared_preferences: ^2.0.15
  fl_chart: 0.55.0
  flutter_local_notifications: ^16.3.2



  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4

  shared_preferences: any
dependency_overrides:
  intl: ^0.19.0
  firebase_core: ^3.4.1
  web: ^0.5.1


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/projects/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800