// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

import 'package:firebase_core/firebase_core.dart';

// ...


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBRj84Wtq_ErrsBRMLqP7L7dj8dbX_gSY',
    appId: '1:956792943125:web:a2b5201ab78c59778cd41c',
    messagingSenderId: '956792943125',
    projectId: 'hardwarechat-3da37',
    authDomain: 'hardwarechat-3da37.firebaseapp.com',
    storageBucket: 'hardwarechat-3da37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtF9BPngN9RoyhKBhnE54ng7EcT_8158',
    appId: '1:956792943125:android:b6baf451e1b1285b8cd41c',
    messagingSenderId: '956792943125',
    projectId: 'hardwarechat-3da37',
    storageBucket: 'hardwarechat-3da37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKyrFIdZuGIx1hP7Mw_IQK18C4Z6Y0d9g',
    appId: '1:956792943125:ios:325a4f6bf209d5948cd41c',
    messagingSenderId: '956792943125',
    projectId: 'hardwarechat-3da37',
    storageBucket: 'hardwarechat-3da37.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );

}